manager/urls.py
from django.conf.urls import url
from manager.views.manager_views import CreateCategoryView, ShowCategoriesView, ShowUsersView, DeleteUserView

urlpatterns = \
    [
        url(r'^$', CreateCategoryView.as_view(), name='index'),
        url(r'^show-categories/$', ShowCategoriesView.as_view(), name='show_categories'),
        url(r'^show-users/$', ShowUsersView.as_view(), name='show_users'),
        url(r'^delete-user/(?P<member_id>\d+)/', DeleteUserView.as_view(), name='delete_user')
    ]

taskrabbit/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from taskrabbit import settings
from user.views.search_views import Search

urlpatterns = \
    [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^manager/', include('manager.urls', namespace='manager')),
        url(r'^service/', include('service.urls', namespace='service')),

        url(r'^', include('user.urls', namespace='user')),
        url(r'^review/', include('review.urls', namespace='review')),
        url(r'^search/', Search.as_view(), name='search')

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
import user
import user.views.user_views
from django.conf.urls import url

urlpatterns = \
    [
        url(r'^login/', user.views.user_views.login_user, name='login'),
        url(r'^registration/', user.views.user_views.registration, name='registration'),
        url(r'^$', user.views.user_views.index, name='index'),
        url(r'^logout/$', user.views.user_views.logout_user, name='logout'),
        url(r'^accounts/confirm/(?P<activation_key>\w+)/', user.views.user_views.register_confirm,
            name='confirm_account'),
        url(r'^profile-customer/(?P<customer_id>\d+)/$', user.views.user_views.profile_user, name='profile_customer'),
        url(r'^edit-customer-profile', user.views.user_views.edit_customer_profile, name='edit-customer-profile')
    ]

manager/models.py
from django.db import models

# Create your models here.

manager/forms/category_form.py
from django.forms import ModelForm
from service.models import Category


class CreateCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

        labels = {
            "name": 'نام دسته بندی',
            "image": 'عکس'
        }

manager/views/manager_views.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import redirect

from django.views.generic import FormView, ListView, TemplateView

from manager.forms.category_form import CreateCategoryForm
from service.models import Category
from user.models import Member


class CreateCategoryView(FormView):
    template_name = 'manager/index.html'
    form_class = CreateCategoryForm

    def form_valid(self, form):
        form.save()

        return redirect(reverse('manager:show_categories'))


class ShowCategoriesView(ListView):
    model = Category
    template_name = 'manager/show_categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.all()


class ShowUsersView(ListView):
    model = Member
    template_name = 'manager/show_users.html'
    context_object_name = 'members'

    def get_queryset(self):
        return Member.objects.all()


class DeleteUserView(TemplateView):
    template_name = 'manager/index.html'

    def get(self, request, *args, **kwargs):
        user_id = self.kwargs['member_id']
        member = Member.objects.get(id=user_id)
        member.user.delete()
        return HttpResponse('')

manager/templates/manager/index.html
{% extends 'manager/logged_in_manager.html' %}
{% load static %}

{% block container %}
    <div class="container" dir="rtl">
        <div class="px-40 vertical spacer"></div>
        <div class="row">
            <div class="col s12 m2">&nbsp;</div>
            <div class="col s12 m8">
                <ul class="collapsible" data-collapsible="accordion">
                    <li>
                        <div class="collapsible-header lime lighten-4"><i class="icon-cart"></i>ثبت دسته بندی</div>
                        <div class="collapsible-body">

                            <form enctype="multipart/form-data" method="post">
                                {% csrf_token %}
                                <div class="card">
                                    <div class="card-content">
                                        {% for field in form %}
                                            {{ field.label }}
                                            <br/><br/>
                                            <p dir="rtl">{{ field }}</p>
                                            <div dir="rtl" class="error-msg">{{ field.errors }}</div>
                                        {% endfor %}
                                        <br/>
                                        <button name="member-reg-btn" type="submit"
                                                class="waves-effect waves-light btn full width">ثبت دسته بندی
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>
                </ul>


            </div>
            <div class="col s12 m2">&nbsp;</div>
        </div>

    </div>

{% endblock %}

manager/templates/manager/logged_in_manager.html
{% extends 'layout.html' %}
{% load static %}
{% block navbar %}

    <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'user:logout' %}" class="normal navbar item">خروج</a></li>
        <li><a href="" class="normal navbar dropdown-button item"
               data-activates="menu-links-1">نمایش</a>
            <ul id="menu-links-1" class="dropdown-content">
                <li><a href="{% url 'manager:show_categories' %}">دسته‌ها</a></li>
                <li><a href="{% url 'manager:show_users' %}">کاربران</a></li>
            </ul>
        </li>


        <li><a href="{% url 'manager:index' %}" class="normal navbar item">پنل مدیریت</a></li>

    </ul>
    <div dir="rtl">{{ message }}</div>


    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>

{% endblock %}
{% block container %}

{% endblock %}

manager/templates/manager/show_categories.html
{% extends 'manager/logged_in_manager.html' %}

{% block container %}
    <div class="container">
        <div class="row">
            {% for category in categories %}


                <div class="col s12 m3 ">
                    <div class="card " dir="rtl">
                        <div class="card-image">
                            <img src="{{ category.image.url }}">
                            <span class="card-title red-text">{{ category.name }}</span>
                        </div>

                    </div>

                </div>



            {% endfor %}
        </div>
    </div>
{% endblock %}

manager/templates/manager/show_users.html
{% extends 'manager/logged_in_manager.html' %}
{% load static %}

{% block container %}
    <div class="container">
        <div class="row" dir="rtl">
            {% for member in members %}
                <div class="right col s12 m3 post">
                    <div class="card ">
                        <a href="#"></a>

                        <div class="card-image waves-effect waves-block waves-light">
                            <img src="{{ member.image.url }}">
                        </div>
                        <div class="card-content">{{ member.full_name }}<br/>{{ member.city }}</div>
                        <div class="card-action">
                            <a href="{% url 'service:tasker_profile' member.id %}">نمایش حساب کارمندی</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}