taskrabbit/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from taskrabbit import settings
from user.views.search_views import Search

urlpatterns = \
    [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^manager/', include('manager.urls', namespace='manager')),
        url(r'^service/', include('service.urls', namespace='service')),

        url(r'^', include('user.urls', namespace='user')),
        url(r'^review/', include('review.urls', namespace='review')),
        url(r'^search/', Search.as_view(), name='search')

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
import user
import user.views.user_views
from django.conf.urls import url

urlpatterns = \
    [
        url(r'^login/', user.views.user_views.login_user, name='login'),
        url(r'^registration/', user.views.user_views.registration, name='registration'),
        url(r'^$', user.views.user_views.index, name='index'),
        url(r'^logout/$', user.views.user_views.logout_user, name='logout'),
        url(r'^accounts/confirm/(?P<activation_key>\w+)/', user.views.user_views.register_confirm,
            name='confirm_account'),
        url(r'^profile-customer/(?P<customer_id>\d+)/$', user.views.user_views.profile_user, name='profile_customer'),
        url(r'^edit-customer-profile', user.views.user_views.edit_customer_profile, name='edit-customer-profile')
    ]

review/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime
from django.db import models

# Create your models here.


class CommentSet(models.Model):
    def __str__(self):
        return str(self.id)


class DateMixin(models.Model):
    date = models.DateTimeField(auto_now_add=True)

    def elapsed_time(self):
        time_delta = datetime.now() - self.date
        seconds = time_delta.seconds
        if seconds < 60:
            return "چند لحظه پیش"
        if seconds < 3600:
            return str(int(seconds / 60)) + " دقیقه پیش"
        if time_delta.days < 1:
            return str(int(seconds / 3600)) + " ساعت پیش"
        if time_delta.days < 365:
            return str(int(time_delta.days)) + " روز پیش"
        return self.date.date


class Comment(DateMixin):
    context = models.TextField("متن نظر")
    comment_set = models.ForeignKey('CommentSet', related_name='comments')
    author = models.ForeignKey('user.Member', related_name='comments')

    class Meta:
        verbose_name_plural = 'کامنت ها'
        verbose_name = 'کامنت'

    def __str__(self):
        return self.context


class Rate(models.Model):
    order = models.OneToOneField('service.Order', related_name='rate')
    customer = models.ForeignKey('user.Member', related_name='customer')  # todo inja afzoonegi darim
    rate = models.PositiveSmallIntegerField("نمره", default=0)

    class Meta:
        verbose_name_plural = 'امتیازها'
        verbose_name = 'امتیاز'

    def save(self, **kwargs):
        skill = self.order.skill
        skill_rate_num = skill.orders.filter(status='D').count()
        skill.rate = (skill_rate_num * skill.rate + self.rate) / (skill_rate_num + 1)
        skill.save()
        member = self.order.skill.tasker
        order_rate_count = member.get_done_sales_count()
        member.rate = (order_rate_count * member.rate + self.rate) / (order_rate_count + 1)
        member.save()
        super(Rate, self).save()

service/models.py
import random

from django.db import models

# Create your models here.
from review.models import CommentSet


class Skill(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    category = models.ForeignKey('Category', related_name='skills')
    price = models.IntegerField()
    image = models.ImageField(upload_to='skill_images')
    tasker = models.ForeignKey('user.Member', related_name='skills')
    rate = models.FloatField(default=0)
    comment_set = models.OneToOneField('review.CommentSet', related_name='skill')

    def get_score(self):
        orders = self.orders.all()
        scores = 0
        for order in orders:
            if order.status == 'D':
                scores += order.rate.rate
        return scores, orders.count()

    def __str__(self):
        return str(self.title) + " " + str(self.category)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.comment_set = CommentSet.objects.create()
        else:
            print(self.pk)
        super(Skill, self).save()


ORDER_STATUS = (
    ('P', 'در حال انجام'),
    ('D', 'انجام شده')
)


class Order(models.Model):
    customer = models.ForeignKey('user.Member', related_name='orders')
    skill = models.ForeignKey('Skill', related_name='orders')
    code = models.IntegerField()
    order_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=ORDER_STATUS, default='P', null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.code = random.randint(1000000, 9999999)
        super(Order, self).save()


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category_images')

    def __str__(self):
        return self.name
        # todo bayad image ham dashte bashe

user/models.py
# Create your models here.
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.aggregates import Avg

from review.models import CommentSet
from service.models import Order

GENDER_CHOICES = (
    ('M', 'مرد'),
    ('F', 'زن'),
)


class Member(models.Model):
    user = models.OneToOneField(User, related_name='member')
    full_name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=12)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M', null=True)
    city = models.CharField(max_length=25)
    address = models.CharField(max_length=150)
    image = models.ImageField(upload_to='profile_images', default='/media/profile_images/profile-image-default.jpg')
    rate = models.FloatField(default=0)  # just for performance
    # confirmation
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=datetime.date.today)
    comment_set = models.OneToOneField('review.CommentSet', related_name='member')
    credit = models.IntegerField(default=0)

    def get_orders_count(self):
        return self.orders.count()  # mige ke har ki che ghad kharid karde

    def get_sales_count(self):  # te'dade kharid haie ke azash shodaro mige
        return Order.objects.filter(skill__tasker=self).count()

    def get_done_sales_count(self):
        return Order.objects.filter(skill__tasker=self, status='D').count()

    def get_score(self):
        query = Order.objects.filter(skill__tasker=self, status='D').aggregate(average=Avg('rate__rate'))
        return query['average']

    class Meta:
        verbose_name_plural = 'کاربران نوع مشتری'
        verbose_name = 'کاربر نوع مشتری'

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.pk:
            self.comment_set = CommentSet.objects.create()
        super(Member, self).save()

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

from user.forms import CustomerRegForm, LoginForm, AdditionalInfo


def index(request):
    return render(request, 'index.html', {})


def registration(request):
    if request.method == "POST":
        if 'member-reg-btn' in request.POST:
            customer_reg_form = CustomerRegForm(request.POST)

            if customer_reg_form.is_valid():
                email = customer_reg_form.cleaned_data['customer_email']
                password = customer_reg_form.cleaned_data['customer_password']
                user = User.objects.create_user(email=email, password=password, username=email)
                user.save()
                customer_reg = customer_reg_form.save(commit=False)
                customer_reg.user = user
                customer_reg.save()
                return HttpResponseRedirect('/')
            else:
                return render(request, 'registration.html', {'customer_reg_form': customer_reg_form})
    else:
        customer_reg_form = CustomerRegForm()
        return render(request, 'registration.html', {'customer_reg_form': customer_reg_form})


def login_user(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)

        if login_form.is_valid():
            email = login_form.cleaned_data['email']
            password = login_form.cleaned_data['password']

            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
            msg = "نام کاربری یا کلمه عبور نامعتبر است."
            return render(request, 'login.html', {'login_form': login_form, 'msg': msg})
        else:
            return render(request, 'login.html', {'login_form': login_form})
    else:
        login_form = LoginForm()
        return render(request, 'login.html', {'login_form': login_form})


def additional_info(request):
    if request.method == "POST":
        additional_info_form = AdditionalInfo(request.POST)
        if additional_info_form.is_valid():
            pass

        else:
            return render(request, 'additional-info.html', {'additional_info_form': additional_info_form})

    else:
        additional_info_form = AdditionalInfo()
        return render(request, 'additional-info.html',
                      {'additional_info_form': additional_info_form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

user/views/search_views.py
from django.shortcuts import render
from django.views.generic.edit import FormView

from service.models import Skill
from user.forms import SearchForm


class Search(FormView):
    template_name = 'search.html'
    form_class = SearchForm

    def form_valid(self, form):
        data = form.cleaned_data
        skill_name = data['skill_name']
        city = data['city']
        location = data['location']
        max_price = data['max_price']
        min_rate = data['min_rate']
        context = self.get_context_data()
        skills = Skill.objects.filter(price__lte=max_price).filter(rate__gte=min_rate).filter(
                title__contains=skill_name).filter(tasker__city__contains=city).filter(
            tasker__address__contains=location)
        context['skills'] = skills
        return render(self.request, template_name=self.template_name, context=context)

user/views/user_views.py
import datetime
import hashlib
import random

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models.aggregates import Count
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.shortcuts import render

from review.forms import CommentForm, RatingForm
from service.models import Order, Skill
from user.forms import CustomerRegForm, LoginForm
from user.forms import EditCustomerProfileForm
from user.models import Member


def index(request):
    if request.session.get('last_visit'):
        last_visit_time = request.session.get('last_visit')
        visits = request.session.get('visits', 0)
        if (datetime.datetime.now() - datetime.datetime.strptime(last_visit_time[:-7], "%Y-%m-%d %H:%M:%S")).days >= 0:
            request.session['visits'] = visits + 1
            request.session['last_visit'] = str(datetime.datetime.now())

    else:
        request.session['last_visit'] = str(datetime.datetime.now())
        request.session['visits'] = 1

    count = request.session.get('visits') if request.session.get('visits') else 0
    members = Member.objects.all()
    skills = Skill.objects.all()
    best_taskers = Member.objects.exclude(skills__isnull=True).order_by('-rate')[:3]
    best_members = Member.objects.annotate(orders_num=Count('orders')).order_by('-orders_num')[:3]
    return render(request, 'index.html',
                  {'visits': count, 'best_members': best_members, 'best_taskers': best_taskers, 'members': members,
                   'skills': skills})


def registration(request):
    if request.method == "POST":
        if 'member-reg-btn' in request.POST:
            customer_reg_form = CustomerRegForm(request.POST)

            if customer_reg_form.is_valid():
                username = customer_reg_form.cleaned_data['full_name']
                email = customer_reg_form.cleaned_data['member_email']
                password = customer_reg_form.cleaned_data['member_password']

                mobile_number = customer_reg_form.cleaned_data['mobile_number']
                gender = customer_reg_form.cleaned_data['gender']
                city = customer_reg_form.cleaned_data['city']
                address = customer_reg_form.cleaned_data['address']

                user = User.objects.create_user(email=email, password=password, username=username)
                user.is_active = False
                user.save()
                logout(request)

                salt = hashlib.sha1(str(random.random()).encode('utf-8')).hexdigest()[:5]
                activation_key = hashlib.sha1((salt + email).encode('utf-8')).hexdigest()
                key_expires = datetime.datetime.today() + datetime.timedelta(2)

                new_member = Member(user=user, activation_key=activation_key, key_expires=key_expires,
                                    mobile_number=mobile_number, gender=gender, city=city, address=address,
                                    full_name=username)
                new_member.save()

                # send email
                email_subject = 'تأیید حساب کاربری'
                email_body = "سلام %s,\n" \
                             "با تشکر از شما بابت ثبت نام در سایت خدمت گزار، لطفا از طریق لینک زیر تا ۴۸ ساعت " \
                             "آینده حساب کاربری خود را فعال نمایید.\n\
                           http://127.0.0.1:8000/accounts/confirm/%s" % (username, activation_key)

                send_mail(email_subject, email_body, 'aaghamohammadi@ce.sharif.edu',
                          [email], fail_silently=False)
                return HttpResponseRedirect('/')

            else:
                return render(request, 'registration.html', {'customer_reg_form': customer_reg_form})
    else:
        customer_reg_form = CustomerRegForm()
        return render(request, 'registration.html', {'customer_reg_form': customer_reg_form})


def login_user(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)

        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if not user.is_active:
                    msg = "لطفا از طریق ایمیل فعال سازی، حساب کاربری خود را فعال نمایید."
                    return render(request, 'login.html', {'login_form': login_form, 'msg': msg})
                login(request, user)
                return HttpResponseRedirect('/')
            msg = "نام کاربری یا کلمه عبور نامعتبر است."
            return render(request, 'login.html', {'login_form': login_form, 'msg': msg})
        else:
            return render(request, 'login.html', {'login_form': login_form})
    else:
        login_form = LoginForm()
        return render(request, 'login.html', {'login_form': login_form})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def register_confirm(request, activation_key):
    if request.user.is_authenticated():
        HttpResponseRedirect('/')

    user_member = get_object_or_404(Member, activation_key=activation_key)

    if user_member.key_expires < datetime.datetime.now():
        return render_to_response('confirm_expired.html')

    user = user_member.user
    user.is_active = True
    user.save()
    return render_to_response('confirm.html')


def profile_user(request, customer_id):
    member = Member.objects.get(user=request.user)
    # print()
    order_set = Order.objects.filter(customer=member)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        rating_form = RatingForm(request.POST)

    else:
        comment_form = CommentForm()
        rating_form = RatingForm()
        template_name = 'profile-customer.html'

        return render(request, template_name,
                      {'member': member, 'comment_form': comment_form, 'rating_form': rating_form,
                       'order_set': order_set})


def edit_customer_profile(request):
    template_name = 'edit-customer-profile.html'
    member = Member.objects.get(user=request.user)
    if request.method == "POST":
        form = EditCustomerProfileForm(instance=member, data=request.POST)
        if form.is_valid():
            image = form.cleaned_data['image']
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = EditCustomerProfileForm(instance=member)
    return render(request, template_name, {'form': form})

user/templates/confirm_expired.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

user/templates/customer_mode.html
{% extends 'layout.html' %}
{% block navbar %}
    <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'user:edit-customer-profile' %}" class="normal navbar item">دیدن دسته‌ها</a></li>
        <li><a href="{% url 'user:edit-customer-profile' %}" class="normal navbar item">مشاهده‌ی سفارشات</a></li>
        <li><a href="#" class="normal navbar item">وضعیت کارگذار</a></li>
    </ul>
{% endblock %}

user/templates/guest_user.html
{% extends 'layout.html' %}
{% block navbar %}
    <ul class="right hide-on-med-and-down">

            <li><a href="{% url 'user:registration' %}" class="normal navbar item">ثبت نام</a></li>

        <li><a href="{% url 'user:login' %}" class="normal navbar dropdown-button item"
               data-activates="menu-links-1">ورود</a>
        </li>
        <li class="active"><a href="#" class="normal navbar item">صفحه اصلی</a></li>

    </ul>


    <ul id="nav-mobile" class="side-nav">
        <li class="active"><a href="#">صفحه ی اصلی</a></li>
        <li><a href="{% url 'user:login' %}">ورود</a></li>
        <li><a href="{% url 'user:registration' %}">ثبت نام</a></li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>

{% endblock %}

user/templates/index.html
{% extends user.is_authenticated|yesno:"logged_in_user.html,guest_user.html" %}
{#{% extends 'logged_in_user.html' %}#}
{% load staticfiles %}
{% load static %}
{% block title %}
    سامانه برون سپاری محلی کارها
{% endblock %}

{% block static_css %}

{% endblock %}
{##}
{#{% block navbar %}#}
{#    <ul class="right hide-on-med-and-down">#}
{#        {% if not user.is_authenticated %}#}
{#            <li><a href="{% url 'user:registration' %}" class="normal navbar item">ثبت نام</a></li>#}
{#        {% endif %}#}
{##}
{#        <li><a href="{% url 'user:login' %}" class="normal navbar dropdown-button item"#}
{#               data-activates="menu-links-1">#}
{#            {% if user.is_authenticated %}#}
{#                حساب کاربری#}
{#            {% else %}#}
{#                ورود#}
{#            {% endif %}</a>#}
{#            <ul id="menu-links-1" class="dropdown-content">#}
{#                {% if user.is_authenticated %}#}
{#                    <li><a href="{% url 'user:edit-customer-profile' %}">ویرایش حساب کاربری</a></li>#}
{#                    <li><a href="{% url 'user:profile_customer' user.id %}">حساب کاربری</a></li>#}
{#                    <li><a href="{% url 'service:edit_skill' %}">ثبت مهارت</a></li>#}
{#                    <li><a href="/logout/">خروج</a></li>#}
{#                {% endif %}#}
{##}
{##}
{#            </ul>#}
{#        </li>#}
{#        <li class="active"><a href="#" class="normal navbar item">صفحه اصلی</a></li>#}
{##}
{#    </ul>#}
{##}
{##}
{#    <ul id="nav-mobile" class="side-nav">#}
{#        <li class="active"><a href="#">صفحه ی اصلی</a></li>#}
{#        <li><a href="{% url 'user:login' %}">ورود</a></li>#}
{#        <li><a href="{% url 'user:registration' %}">ثبت نام</a></li>#}
{#    </ul>#}
{#    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>#}
{##}
{#{% endblock %}#}

{% block container %}
    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>

                <h1 class="header center teal-text text-lighten-2">بهتر زندگی کنید</h1>

                <div class="row center">
                    <h5 class="header col s12 light">خدمت گزار تنها چند کلیک با خانه شما فاصله دارد</h5>
                </div>
                <br><br>

            </div>
        </div>
        <div class="parallax"><img src="{% static "images/user/background.jpg" %}" alt="background image"></div>
    </div>


    <div class="container">
        <div class="section">

            <!--   Icon Section   -->
            <div class="row">
                <div class="col s12 m4">
                    <div class="card-panel teal" dir="rtl">
                         <span class="white-text">
                            <strong>تعداد بازدید کنندگان: </strong>{{ visits }}<br/>
                             <strong>تعداد کاربران بر خط: </strong>{{ request.online_now }}<br/>
                             <strong>تعداد کارفرمایان: </strong>{{ members.count }}<br/>
                             <strong>تعداد خدمات:</strong>{{ skills.count }}
                         </span>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center brown-text"><i class="icon-user-check"></i></h2>
                        <h5 class="center">انتخاب خدمت گزار</h5>

                        <p class="light" dir="rtl">تمامی خدمت گزاران با دقت مورد ارزیابی قرار گرفته اند.</p>
                    </div>
                </div>

                {#                <div class="col s12 m4">#}
                {#                    <div class="search" dir="rtl">#}
                {#                        <div class="search-wrapper card">#}
                {#                            <input id="search" placeholder="جست و جو مهارت ...">#}
                {#                            <i class="icon-search"></i>#}
                {#                        </div>#}
                {#                    </div>#}
                {##}
                {#                </div>#}

            </div>
            <div class="row" dir="rtl">
                <h3>پرکارترین کارفرمایان</h3><br/><br/>
                {% for member in best_members %}
                    <div class="right col s12 m3 post">
                        <div class="card">
                            <a href="#"></a>

                            <div class="card-image waves-effect waves-block waves-light">
                                <img src="{{ member.image.url }}">
                            </div>
                            <div class="card-content">{{ member.full_name }}<br/>{{ member.city }}</div>
                            <div class="card-action">
                                <a href="#" class="teal-text">تعداد سفارشات: {{ member.orders.count }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row" dir="rtl">
                <h3>برترین کارمندان</h3><br/><br/>
                {% for tasker in best_taskers %}
                    <div class="right col s12 m3 post" dir="rtl">
                        <div class="card">
                            <a href="#"></a>

                            <div class="card-image waves-effect waves-block waves-light">
                                <img src="{{ tasker.image }}">
                            </div>
                            <div class="card-content">{{ tasker.full_name }}<br/>{{ tasker.city }}<br/>
                            </div>
                            <div class="card-action">
                                <a href="#" class="teal-text">امتیاز: {{ tasker.rate }}</a>
                            </div>


                        </div>
                    </div>
                {% endfor %}
            </div>


        </div>
    </div>

{% endblock %}

{% block footer %}

{% endblock %}

{% block script %}

{% endblock %}

user/templates/logged_in_user.html
{% extends 'layout.html' %}
{% load static %}
{% block navbar %}
    {% if not user.is_superuser %}
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'user:logout' %}" class="normal navbar item">خروج</a></li>
            <li><a href="{% url 'search' %}" class="normal navbar item">جستجو</a></li>
            <li><a href="" class="normal navbar dropdown-button item"
                   data-activates="menu-links-1">نمایش</a>
                <ul id="menu-links-1" class="dropdown-content">
                    <li><a href="{% url 'service:show_categories' %}">دسته‌ها</a></li>
                    <li><a href="{% url 'service:show_taskers' %}">کارمند‌ها</a></li>
                    <li><a href="{% url 'service:show_skills' %}">مهارت‌ها</a></li>

                </ul>
            </li>
            <li><a href="" class="normal navbar dropdown-button item"
                   data-activates="menu-links-2">حساب کاربری</a>
                <ul id="menu-links-2" class="dropdown-content">
                    <li><a href="{% url 'user:edit-customer-profile' %}">ویرایش</a></li>
                    <li><a href="{% url 'user:profile_customer' user.id %}">نمایش</a></li>
                </ul>
            </li>


            <li><a href="{% url 'user:index' %}" class="normal navbar item">صفحه اصلی</a></li>

        </ul>
        <ul class="left hide-on-med-and-down">
            <li><a href="{% url 'service:edit_skill' %}" class="normal navbar  item"
                   data-activates="menu-links-1">ثبت مهارت</a></li>
            <li><a href="{% url 'service:tasker_profile' request.user.member.id %}"
                   class="normal navbar item">حساب کارمندی</a></li>
            <li><a href="{% url 'service:show_customers_orders' %}" class="normal navbar item">سفارشات</a></li>
            <li><a href="{% url 'service:show_my_skills' %}" class="normal navbar item">مهارت‌های من</a></li>
        </ul>
        <div dir="rtl">{{ message }}</div>


        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>
    {% else %}

        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'user:logout' %}" class="normal navbar item">خروج</a></li>
            <li><a href="" class="normal navbar dropdown-button item"
                   data-activates="menu-links-1">نمایش</a>
                <ul id="menu-links-1" class="dropdown-content">
                    <li><a href="{% url 'manager:show_categories' %}">دسته‌ها</a></li>
                    <li><a href="{% url 'manager:show_users' %}">کاربران</a></li>
                </ul>
            </li>


            <li><a href="{% url 'manager:index' %}" class="normal navbar item">پنل مدیریت</a></li>

        </ul>
        <div dir="rtl">{{ message }}</div>


        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>
    {% endif %}


{% endblock %}
{% block container %}

{% endblock %}

user/templates/registration.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load apptags %}
{% block title %}
    ثبت نام کاربر
{% endblock %}
{% block static_css %}
    <link href="{% static "css/user/user.css" %}" rel="stylesheet" media="screen,projection"/>
{% endblock %}
{% block navbar %}
    <ul class="right hide-on-med-and-down">
        <li class="active"><a href="{% url 'user:registration' %}" class="normal navbar item">ثبت نام</a></li>
        <li><a href="{% url 'user:login' %}" class="normal navbar dropdown-button item"
               data-activates="menu-links-1">
            {% if user.is_authenticated %}
                حساب کاربری
            {% else %}
                ورود
            {% endif %}</a>
            <ul id="menu-links-1" class="dropdown-content">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user:edit-customer-profile' %}">ویرایش حساب کاربری</a></li>
                    <li><a href="{% url 'user:profile_customer' user.id %}">حساب کاربری</a></li>
                    <li><a href="{% url 'user:profile_tasker' user.id %}">حساب کارمندی</a></li>
                    <li><a href="/logout/">خروج</a></li>
                {% endif %}


            </ul>
        </li>
        <li><a href="{% url 'user:index' %}" class="normal navbar item">صفحه اصلی</a></li>

    </ul>


    <ul id="nav-mobile" class="side-nav">
        <li class="active"><a href="#">صفحه ی اصلی</a></li>
        <li><a href="{% url 'user:login' %}">ورود</a></li>
        <li><a href="{% url 'user:registration' %}">ثبت نام</a></li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="icon-list2"></i></a>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="px-40 vertical spacer"></div>
        <div class="row">
            <div class="col s12 m2">&nbsp;</div>
            <div class="col s12 m8">
            <p dir="rtl">
                در صورت ثبت نام موفقیت آمیز ایمیل فعال سازی حساب کاربری  ارسال خواهد شد.
            </p>
                <form method="post">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-content">
                            {% for field in customer_reg_form %}
                                {% if field|field_type == "RadioSelect" %}
                                    <div dir="rtl">
                                        {% for radio in field %}
                                            {{ radio.tag }}
                                            <label for="gender_{{ forloop.counter0 }}">{{ radio.choice_label }}</label>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    <div class="input-field left-align" dir="rtl">
                                        {{ field }}
                                        <label>{{ field.label }}</label>
                                    </div>
                                {% endif %}


                                <div dir="rtl" class="error-msg">{{ field.errors }}</div>

                            {% endfor %}
                            <button name="member-reg-btn" type="submit"
                                    class="waves-effect waves-light btn full width">ثبت نام
                            </button>
                        </div>
                    </div>


                </form>


            </div>
            <div class="col s12 m2">&nbsp;</div>
        </div>
    </div>
{% endblock %}