service/urls.py
from service.service_views import EditSkillView, TaskerProfileView, ShowSkillView, ShowCategoriesView, ShowCustomersOrders, \
    ShowCategorySkills, ShowSkillsView, ShowTaskersView, ShowFactorView, RecordOrderView
from django.conf.urls import url

__author__ = 'garfild'

urlpatterns = \
    [
        url(r'^show_categories/$', ShowCategoriesView.as_view(), name='show_categories'),
        url(r'^show-category-skills/(?P<category_id>\d+)/', ShowCategorySkills.as_view(),
            name='show_category_skills'),
        url(r'edit-skill/', EditSkillView.as_view(), name='edit_skill'),
        url(r'show-my-skills/$', TaskerProfileView.as_view(), name='show_my_skills'),
        url(r'tasker-profile/(?P<tasker_id>\d+)/$', TaskerProfileView.as_view(), name='tasker_profile'),
        url(r'show-skills/$', ShowSkillsView.as_view(), name='show_skills'),
        url(r'show-skill/(?P<tasker_id>\d+)/(?P<skill_id>\d+)/$', ShowSkillView.as_view(), name='show_skill'),
        url(r'show-customers-orders/', ShowCustomersOrders.as_view(), name='show_customers_orders'),
        url(r'show-taskers/', ShowTaskersView.as_view(), name='show_taskers'),
        url(r'show-factor/(?P<skill_id>\d+)/', ShowFactorView.as_view(), name='show_factor'),
        url(r'record-order/(?P<skill_id>\d+)/', RecordOrderView.as_view(), name='record_order')
    ]

taskrabbit/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from taskrabbit import settings
from user.views.search_views import Search

urlpatterns = \
    [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^manager/', include('manager.urls', namespace='manager')),
        url(r'^service/', include('service.urls', namespace='service')),

        url(r'^', include('user.urls', namespace='user')),
        url(r'^review/', include('review.urls', namespace='review')),
        url(r'^search/', Search.as_view(), name='search')

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
import user
import user.views.user_views
from django.conf.urls import url

urlpatterns = \
    [
        url(r'^login/', user.views.user_views.login_user, name='login'),
        url(r'^registration/', user.views.user_views.registration, name='registration'),
        url(r'^$', user.views.user_views.index, name='index'),
        url(r'^logout/$', user.views.user_views.logout_user, name='logout'),
        url(r'^accounts/confirm/(?P<activation_key>\w+)/', user.views.user_views.register_confirm,
            name='confirm_account'),
        url(r'^profile-customer/(?P<customer_id>\d+)/$', user.views.user_views.profile_user, name='profile_customer'),
        url(r'^edit-customer-profile', user.views.user_views.edit_customer_profile, name='edit-customer-profile')
    ]

service/models.py
import random

from django.db import models

# Create your models here.
from review.models import CommentSet


class Skill(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    category = models.ForeignKey('Category', related_name='skills')
    price = models.IntegerField()
    image = models.ImageField(upload_to='skill_images')
    tasker = models.ForeignKey('user.Member', related_name='skills')
    rate = models.FloatField(default=0)
    comment_set = models.OneToOneField('review.CommentSet', related_name='skill')

    def get_score(self):
        orders = self.orders.all()
        scores = 0
        for order in orders:
            if order.status == 'D':
                scores += order.rate.rate
        return scores, orders.count()

    def __str__(self):
        return str(self.title) + " " + str(self.category)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.comment_set = CommentSet.objects.create()
        else:
            print(self.pk)
        super(Skill, self).save()


ORDER_STATUS = (
    ('P', 'در حال انجام'),
    ('D', 'انجام شده')
)


class Order(models.Model):
    customer = models.ForeignKey('user.Member', related_name='orders')
    skill = models.ForeignKey('Skill', related_name='orders')
    code = models.IntegerField()
    order_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=ORDER_STATUS, default='P', null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.code = random.randint(1000000, 9999999)
        super(Order, self).save()


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category_images')

    def __str__(self):
        return self.name
        # todo bayad image ham dashte bashe

service/forms/skill_form.py
from django.forms.models import ModelForm
from django import forms
from django.forms.widgets import Select, Textarea, TextInput

from service.models import Skill, Category

__author__ = 'garfild'


class SkillForm(ModelForm):
    title = forms.CharField(widget=TextInput(attrs={'placeholder': 'من میتونم ...'}), label='عنوان')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='دسته‌بندی',
                                      widget=Select(attrs={'class': 'browser-default'}))

    description = forms.CharField(widget=Textarea(attrs={'class': 'materialize-textarea'}),
                                  label='شرح کامل خدمت')

    class Meta:
        model = Skill
        exclude = ['tasker', 'comment_set', 'rate']
        labels = {
            'category': 'دسته‌بندی‌‌',
            'price': 'قیمت',
            'image': 'عکس'
        }

service/templates/service/edit_skill.html
{% extends 'logged_in_user.html' %}
{% load static %}

{% block container %}
    <div class="container" dir="rtl" >
        <div class="px-40 vertical spacer"></div>
        <div class="row">
            <div class="col s12 m2">&nbsp;</div>
            <div class="col s12 m8">
                <form enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-content">
                            {% for field in form %}
                                {{ field.label }}
                                <br/><br/>
                                <p dir="rtl">{{ field }}</p>
                                <div dir="rtl" class="error-msg">{{ field.errors }}</div>
                            {% endfor %}
                        <br/>
                            <button name="member-reg-btn" type="submit"
                                    class="waves-effect waves-light btn full width">ثبت مهارت
                            </button>
                        </div>
                    </div>


                </form>


            </div>
            <div class="col s12 m2">&nbsp;</div>
        </div>

    </div>

{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>
{% endblock %}

service/templates/service/show_categories.html
{% extends 'logged_in_user.html' %}

{% block container %}
    <div class="container">
        <div class="row">
            {% for category in categories %}


                <div class="col s12 m4 ">
                    <div class="card " dir="rtl">
                        <div class="card-image">
                            <img src="{{ category.image.url }}">
                            <span class="card-title red-text">{{ category.name }}</span>
                        </div>
                        <div class="card-content">
                            <p></p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'service:show_category_skills' category.id %}">نمایش مهارت‌های این دسته</a>

                        </div>
                    </div>

                </div>



            {% endfor %}
        </div>
    </div>
{% endblock %}

service/templates/service/show_category_skills.html
{% extends 'logged_in_user.html' %}
{% load service_tags %}
{% load static %}
{% block container %}
    <div class="container" dir="rtl">
        <div class="row">
            {% for skill in skills.all %}
                <div class="col s12 m6 ">
                    {% show_skill skill 1 %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

service/templates/service/show_customers_order.html
{% extends 'logged_in_user.html' %}
{% block container %}

    <div class="container">
        <div class="row">
            <div class="col s12">
                <ul class="collection" dir="rtl">
                    <li class="collection-item">
                        <table>
                            <thead>
                            <tr>
                                <th>مشتری</th>
                                <th>نام خدمت</th>
                                <th>دسته</th>
                                <th>کد سفارش</th>
                                <th>تاریخ</th>
                                <th>قیمت</th>
                                <th>وضعیت</th>
                            </tr>
                            </thead>
                            {% for order in orders %}

                                <tbody>
                                <tr>
                                    <td>{{ order.customer.full_name }}</td>
                                    <td>{{ order.skill.title }}</td>
                                    <td>{{ order.skill.category }}</td>
                                    <td>{{ order.code }}</td>
                                    <td>{{ order.order_time }}</td>
                                    <td>{{ order.skill.price }}</td>
                                    <td>{{ order.get_status_display }}</td>

                                </tr>
                                </tbody>
                            {% endfor %}

                        </table>
                    </li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

service/templates/service/show_factor.html
{% extends 'logged_in_user.html' %}
{% block container %}
    <div class="container">
        <div class="row">

            <div class="col s6">
                <div dir="rtl">اطلاعات فروشنده</div>
                <ul class="collection" dir="rtl">

                    <li class="collection-item">
                        <strong>نام:</strong>
                        {{ skill.tasker.user.username }}
                    </li>
                    <li class="collection-item">
                        <strong>تلفن همراه:</strong>
                        {{ skill.tasker.mobile_number }}
                    </li>
                    <li class="collection-item">
                        <strong>جنسیت:</strong>
                        {% if skill.tasker.gender == 'M' %}
                            مرد
                        {% else %}
                            زن
                        {% endif %}
                    </li>
                    <li class="collection-item">
                        <strong>شهر:</strong>
                        {{ skill.tasker.city }}
                    </li>
                    <li class="collection-item">
                        <strong>آدرس:</strong>
                        {{ skill.tasker.address }}
                    </li>

                </ul>
            </div>
            <div class="col s6">
                <div dir="rtl">اطلاعات مهارت</div>
                <ul class="collection" dir="rtl">
                    <li class="collection-item">
                        <strong>عنوان:</strong>
                        {{ skill.title }}
                    </li>
                    <li class="collection-item">
                        <strong>دسته:</strong>
                        {{ skill.category }}
                    </li>
                    <li class="collection-item">
                        <strong>قیمت:</strong>
                        {{ skill.price }}
                    </li>
                </ul>
                <a class="right waves-effect waves-light btn order">استخدام</a><br/></div>
            <p class="message right"></p>
        </div>
    </div>
    </div>
{% endblock %}
{% block script %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            console.log("salam");
            var skill_id = {{ skill.id }};
            $('.order').click(function () {
                $.ajax({
                    type: 'get', // GET or POST
                    url: '{% url 'service:record_order' skill.id %}', // the file to call
                    success: function (data) {
                        $('.order').addClass('disabled');
                        $('.message').html("به شما از طرف فروشنده زنگ زده خواهد شد. کد سفارش شما " + data['code'] + " میباشد");
                        var delay = 3000; //Your delay in milliseconds
                        setTimeout(function () {
                            window.location = '{% url 'user:profile_customer' request.user.member.id %}';
                        }, delay);
                    }
                });
                return false;
            });
        });
    </script>
{% endblock %}

service/templates/service/show_skill.html
{% extends 'logged_in_user.html' %}
{% load comment_tags %}
{% load service_tags %}
{% load static %}
{% block container %}
    <div class="container" dir="rtl">
        <div class="row">

            <div class="col s12 m8 offset-m2">
            {% show_skill skill 2 %}

            </div>


        </div>

        {% comment_form_show skill.comment_set %}
    </div>


{% endblock %}
{% block script %}
    {{ block.super }}
    <script src="{% static 'js/review/comment.js' %}"></script>

{% endblock %}

service/templates/service/show_skills.html
{% extends 'logged_in_user.html' %}
{% load service_tags %}
{% load static %}
{% block container %}
    <div class="container" dir="rtl">
        <div class="row">
            {% for skill in skills.all %}
                <div class="col s12 m4 ">
                    {% show_skill skill 1 %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

service/templates/service/show_taskers.html
{% extends 'logged_in_user.html' %}
{% load static %}

{% block container %}
    <div class="container">
        <div class="row" dir="rtl">
            {% for tasker in taskers %}
                <div class="right col s12 m3 post">
                    <div class="card medium">
                        <a href="#"></a>

                        <div class="card-image waves-effect waves-block waves-light">
                            <img src="{{ tasker.image.url }}">
                        </div>
                        <div class="card-content">{{ tasker.full_name }}<br/>{{ tasker.city }}</div>
                        <div class="card-action">
                            <a href="{% url 'service:tasker_profile' tasker.id %}">نمایش حساب کارمندی</a>
                            <a>امتیاز: {{ tasker.rate }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}

service/templates/service/tasker_profile.html
{% extends 'logged_in_user.html' %}
{% load service_tags %}
{% load static %}
{% load comment_tags %}
{% block container %}
    <div class="container" dir="rtl">
        <div class="row">
            <div class="right col s12 m3 post">
                <div class="card medium">
                    <a href="#"></a>

                    <div class="card-image waves-effect waves-block waves-light">
                        <img src="{{ tasker.image.url }}">
                    </div>
                    <div class="card-action">
                        <a>امتیاز: {{ tasker.rate }}</a>
                    </div>
                    <div class="card-content">{{ tasker.full_name }}<br/>{{ tasker.city }}</div>
                    {% if user.is_superuser %}
                        <div class="card-action">
                            <a class="right waves-effect waves-light btn delete-user">
                                حذف کاربر
                            </a>

                            <p class="message right"></p>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col m6">
                <ul class="collection" dir="rtl">

                    <li class="collection-item">
                        <strong>نام کامل:</strong>
                        {{ tasker.user.username }}
                    </li>
                    <li class="collection-item">
                        <strong>تلفن همراه:</strong>
                        {{ tasker.mobile_number }}
                    </li>
                    <li class="collection-item">
                        <strong>جنسیت:</strong>
                        {% if tasker.gender == 'M' %}
                            مرد
                        {% else %}
                            زن
                        {% endif %}
                    </li>
                    <li class="collection-item">
                        <strong>شهر:</strong>
                        {{ tasker.city }}
                    </li>
                    <li class="collection-item">
                        <strong>آدرس:</strong>
                        {{ tasker.address }}
                    </li>

                </ul>
            </div>

        </div>
        <div class="row">
            {% for skill in tasker.skills.all %}


                <div class="col s12 m4 ">

                    {% show_skill skill 2 %}

                </div>



            {% endfor %}
        </div>
    </div>
    {% comment_form_show tasker.comment_set %}
{% endblock %}
{% block script %}
    {{ block.super }}
    <script src="{% static 'js/review/comment.js' %}"></script>
    <script>
        $(document).ready(function () {
            console.log("salam");
            var skill_id = {{ tasker.id }};
            $('.delete-user').click(function () {
                $.ajax({
                    type: 'get', // GET or POST
                    url: '{% url 'manager:delete_user' tasker.id %}', // the file to call
                    success: function (data) {
                        $('.message').html("حساب کاربری فرد متخلف به علت رعایت نکردن قوانین بسته شد.");
                        var delay = 1500; //Your delay in milliseconds
                        setTimeout(function () {
                            window.location = '{% url 'manager:show_users'%}';
                        }, delay);
                    }
                });
                return false;
            });
        });
    </script>

{% endblock %}