service/urls.py
from service.service_views import EditSkillView, TaskerProfileView, ShowSkillView, ShowCategoriesView, ShowCustomersOrders, \
    ShowCategorySkills, ShowSkillsView, ShowTaskersView, ShowFactorView, RecordOrderView
from django.conf.urls import url

__author__ = 'garfild'

urlpatterns = \
    [
        url(r'^show_categories/$', ShowCategoriesView.as_view(), name='show_categories'),
        url(r'^show-category-skills/(?P<category_id>\d+)/', ShowCategorySkills.as_view(),
            name='show_category_skills'),
        url(r'edit-skill/', EditSkillView.as_view(), name='edit_skill'),
        url(r'show-my-skills/$', TaskerProfileView.as_view(), name='show_my_skills'),
        url(r'tasker-profile/(?P<tasker_id>\d+)/$', TaskerProfileView.as_view(), name='tasker_profile'),
        url(r'show-skills/$', ShowSkillsView.as_view(), name='show_skills'),
        url(r'show-skill/(?P<tasker_id>\d+)/(?P<skill_id>\d+)/$', ShowSkillView.as_view(), name='show_skill'),
        url(r'show-customers-orders/', ShowCustomersOrders.as_view(), name='show_customers_orders'),
        url(r'show-taskers/', ShowTaskersView.as_view(), name='show_taskers'),
        url(r'show-factor/(?P<skill_id>\d+)/', ShowFactorView.as_view(), name='show_factor'),
        url(r'record-order/(?P<skill_id>\d+)/', RecordOrderView.as_view(), name='record_order')
    ]

taskrabbit/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from taskrabbit import settings
from user.views.search_views import Search

urlpatterns = \
    [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^manager/', include('manager.urls', namespace='manager')),
        url(r'^service/', include('service.urls', namespace='service')),

        url(r'^', include('user.urls', namespace='user')),
        url(r'^review/', include('review.urls', namespace='review')),
        url(r'^search/', Search.as_view(), name='search')

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
import user
import user.views.user_views
from django.conf.urls import url

urlpatterns = \
    [
        url(r'^login/', user.views.user_views.login_user, name='login'),
        url(r'^registration/', user.views.user_views.registration, name='registration'),
        url(r'^$', user.views.user_views.index, name='index'),
        url(r'^logout/$', user.views.user_views.logout_user, name='logout'),
        url(r'^accounts/confirm/(?P<activation_key>\w+)/', user.views.user_views.register_confirm,
            name='confirm_account'),
        url(r'^profile-customer/(?P<customer_id>\d+)/$', user.views.user_views.profile_user, name='profile_customer'),
        url(r'^edit-customer-profile', user.views.user_views.edit_customer_profile, name='edit-customer-profile')
    ]

service/models.py
import random

from django.db import models

# Create your models here.
from review.models import CommentSet


class Skill(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=500)
    category = models.ForeignKey('Category', related_name='skills')
    price = models.IntegerField()
    image = models.ImageField(upload_to='skill_images')
    tasker = models.ForeignKey('user.Member', related_name='skills')
    rate = models.FloatField(default=0)
    comment_set = models.OneToOneField('review.CommentSet', related_name='skill')

    def get_score(self):
        orders = self.orders.all()
        scores = 0
        for order in orders:
            if order.status == 'D':
                scores += order.rate.rate
        return scores, orders.count()

    def __str__(self):
        return str(self.title) + " " + str(self.category)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.comment_set = CommentSet.objects.create()
        else:
            print(self.pk)
        super(Skill, self).save()


ORDER_STATUS = (
    ('P', 'در حال انجام'),
    ('D', 'انجام شده')
)


class Order(models.Model):
    customer = models.ForeignKey('user.Member', related_name='orders')
    skill = models.ForeignKey('Skill', related_name='orders')
    code = models.IntegerField()
    order_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=ORDER_STATUS, default='P', null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.code = random.randint(1000000, 9999999)
        super(Order, self).save()


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category_images')

    def __str__(self):
        return self.name
        # todo bayad image ham dashte bashe

service/forms/skill_form.py
from django.forms.models import ModelForm
from django import forms
from django.forms.widgets import Select, Textarea, TextInput

from service.models import Skill, Category

__author__ = 'garfild'


class SkillForm(ModelForm):
    title = forms.CharField(widget=TextInput(attrs={'placeholder': 'من میتونم ...'}), label='عنوان')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='دسته‌بندی',
                                      widget=Select(attrs={'class': 'browser-default'}))

    description = forms.CharField(widget=Textarea(attrs={'class': 'materialize-textarea'}),
                                  label='شرح کامل خدمت')

    class Meta:
        model = Skill
        exclude = ['tasker', 'comment_set', 'rate']
        labels = {
            'category': 'دسته‌بندی‌‌',
            'price': 'قیمت',
            'image': 'عکس'
        }

service/templates/service/tags/show_skill.html
{% ifequal num 1 %}
    <div class="card medium">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="{{ skill.image.url }}">
        </div>
        <div class="card-content">
            <span class="card-title activator blue-text"><a
                    href="{% url 'service:show_skill' skill.tasker.id skill.id %}">{{ skill.title }}</a><i
                    class="material-icons right icon-point-up grey-text text-darken-4"></i></span>

        </div>
        <div class="card-action">
            {% ifnotequal request.user.member skill.tasker %}
                <a class="right" href="{% url 'service:show_factor' skill.id %}">استخدام</a>
            {% endifnotequal %}
            <a class="right">{{ skill.price }} تومان</a>
            <a class="right" href="{% url 'service:tasker_profile' skill.tasker.id %}">کاری
                از {{ skill.tasker.user.username }}</a>
            <a class="right">امتیاز: {{ skill.rate }}</a>

        </div>
        <div class="card-reveal">
            <span class="card-title grey-text "><a
                    href="{% url 'service:show_skill' skill.tasker.id skill.id %}">{{ skill.title }}</a><i
                    class="material-icons right icon-point-down"></i></span>
            <p>{{ skill.description }}</p>
        </div>
    </div>
{% else %}
    <div class="card large" dir="rtl">
        <div class="card-image">
            <img src="{{ skill.image.url }}">
            <span class="card-title red-text"><a
                    href="{% url 'service:show_skill' skill.tasker.id skill.id %}">{{ skill.title }}</a></span><br/>

        </div>
        <div class="card-content">
            <p>{{ skill.description }}</p>
        </div>
        <div class="card-action">
            {% ifnotequal request.user.member skill.tasker %}
                <a class="right" href="{% url 'service:show_factor' skill.id %}">استخدام</a>
            {% endifnotequal %}
            <a class="right">{{ skill.price }} تومان</a>
            <a class="right" href="{% url 'service:tasker_profile' skill.tasker.id %}">کاری از
                {{ skill.tasker.user.username }}</a>
            <a class="right" dir="rtl">امتیاز: {{ skill.rate }}</a>
        </div>
    </div>
{% endifequal %}